/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard.inquiries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard.properties'
import { Route as ExitOpportunitiesIndexRouteImport } from './routes/exit-opportunities.index'
import { Route as ExitOpportunitiesSlugRouteImport } from './routes/exit-opportunities.$slug'
import { Route as NewUnitsIndexRouteImport } from './routes/new-units.index'
import { Route as NewUnitsSlugRouteImport } from './routes/new-units.$slug'
import { Route as ProjectOpportunitiesIndexRouteImport } from './routes/project-opportunities.index'
import { Route as ProjectOpportunitiesSlugRouteImport } from './routes/project-opportunities.$slug'
import { Route as PropertySlugRouteImport } from './routes/property/$slug'
import { Route as SellExitIndexRouteImport } from './routes/sell-exit.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin.cities'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/_authenticated/admin.forms'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminNavRouteImport } from './routes/_authenticated/admin.nav'
import { Route as AuthenticatedAdminNewUnitsRouteImport } from './routes/_authenticated/admin.new-units'
import { Route as AuthenticatedAdminProjectOpportunitiesRouteImport } from './routes/_authenticated/admin.project-opportunities'
import { Route as AuthenticatedDashboardExitRequestsRouteImport } from './routes/_authenticated/dashboard.exit-requests'
import { Route as AuthenticatedSellExitNewRouteImport } from './routes/_authenticated/sell-exit.new'
import { Route as AuthenticatedSellExitStatusRouteImport } from './routes/_authenticated/sell-exit.status'
import { Route as AuthenticatedStaffAuditRouteImport } from './routes/_authenticated/staff.audit'
import { Route as AuthenticatedStaffSettingsRouteImport } from './routes/_authenticated/staff.settings'
import { Route as AuthenticatedStaffUsersRouteImport } from './routes/_authenticated/staff.users'
import { Route as NewUnitsLiveIdRouteImport } from './routes/new-units.live.$id'
import { Route as AuthenticatedStaffVerificationIndexRouteImport } from './routes/_authenticated/staff.verification.index'
import { Route as AuthenticatedStaffVerificationIdRouteImport } from './routes/_authenticated/staff.verification.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => DashboardRoute,
} as any)
const ExitOpportunitiesIndexRoute = ExitOpportunitiesIndexRouteImport.update({
  id: '/exit-opportunities/',
  path: '/exit-opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitOpportunitiesSlugRoute = ExitOpportunitiesSlugRouteImport.update({
  id: '/exit-opportunities/$slug',
  path: '/exit-opportunities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUnitsIndexRoute = NewUnitsIndexRouteImport.update({
  id: '/new-units/',
  path: '/new-units/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUnitsSlugRoute = NewUnitsSlugRouteImport.update({
  id: '/new-units/$slug',
  path: '/new-units/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectOpportunitiesIndexRoute =
  ProjectOpportunitiesIndexRouteImport.update({
    id: '/project-opportunities/',
    path: '/project-opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectOpportunitiesSlugRoute =
  ProjectOpportunitiesSlugRouteImport.update({
    id: '/project-opportunities/$slug',
    path: '/project-opportunities/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellExitIndexRoute = SellExitIndexRouteImport.update({
  id: '/sell-exit/',
  path: '/sell-exit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNavRoute = AuthenticatedAdminNavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewUnitsRoute =
  AuthenticatedAdminNewUnitsRouteImport.update({
    id: '/new-units',
    path: '/new-units',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectOpportunitiesRoute =
  AuthenticatedAdminProjectOpportunitiesRouteImport.update({
    id: '/project-opportunities',
    path: '/project-opportunities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardExitRequestsRoute =
  AuthenticatedDashboardExitRequestsRouteImport.update({
    id: '/dashboard/exit-requests',
    path: '/dashboard/exit-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellExitNewRoute =
  AuthenticatedSellExitNewRouteImport.update({
    id: '/sell-exit/new',
    path: '/sell-exit/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellExitStatusRoute =
  AuthenticatedSellExitStatusRouteImport.update({
    id: '/sell-exit/status',
    path: '/sell-exit/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffAuditRoute = AuthenticatedStaffAuditRouteImport.update({
  id: '/staff/audit',
  path: '/staff/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffSettingsRoute =
  AuthenticatedStaffSettingsRouteImport.update({
    id: '/staff/settings',
    path: '/staff/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffUsersRoute = AuthenticatedStaffUsersRouteImport.update({
  id: '/staff/users',
  path: '/staff/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NewUnitsLiveIdRoute = NewUnitsLiveIdRouteImport.update({
  id: '/new-units/live/$id',
  path: '/new-units/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffVerificationIndexRoute =
  AuthenticatedStaffVerificationIndexRouteImport.update({
    id: '/staff/verification/',
    path: '/staff/verification/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffVerificationIdRoute =
  AuthenticatedStaffVerificationIdRouteImport.update({
    id: '/staff/verification/$id',
    path: '/staff/verification/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sale': typeof SaleRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/exit-opportunities/$slug': typeof ExitOpportunitiesSlugRoute
  '/new-units/$slug': typeof NewUnitsSlugRoute
  '/project-opportunities/$slug': typeof ProjectOpportunitiesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/exit-opportunities/': typeof ExitOpportunitiesIndexRoute
  '/new-units/': typeof NewUnitsIndexRoute
  '/project-opportunities/': typeof ProjectOpportunitiesIndexRoute
  '/sell-exit/': typeof SellExitIndexRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/nav': typeof AuthenticatedAdminNavRoute
  '/admin/new-units': typeof AuthenticatedAdminNewUnitsRoute
  '/admin/project-opportunities': typeof AuthenticatedAdminProjectOpportunitiesRoute
  '/dashboard/exit-requests': typeof AuthenticatedDashboardExitRequestsRoute
  '/sell-exit/new': typeof AuthenticatedSellExitNewRoute
  '/sell-exit/status': typeof AuthenticatedSellExitStatusRoute
  '/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/users': typeof AuthenticatedStaffUsersRoute
  '/new-units/live/$id': typeof NewUnitsLiveIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/verification/$id': typeof AuthenticatedStaffVerificationIdRoute
  '/staff/verification/': typeof AuthenticatedStaffVerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sale': typeof SaleRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/exit-opportunities/$slug': typeof ExitOpportunitiesSlugRoute
  '/new-units/$slug': typeof NewUnitsSlugRoute
  '/project-opportunities/$slug': typeof ProjectOpportunitiesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/exit-opportunities': typeof ExitOpportunitiesIndexRoute
  '/new-units': typeof NewUnitsIndexRoute
  '/project-opportunities': typeof ProjectOpportunitiesIndexRoute
  '/sell-exit': typeof SellExitIndexRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/nav': typeof AuthenticatedAdminNavRoute
  '/admin/new-units': typeof AuthenticatedAdminNewUnitsRoute
  '/admin/project-opportunities': typeof AuthenticatedAdminProjectOpportunitiesRoute
  '/dashboard/exit-requests': typeof AuthenticatedDashboardExitRequestsRoute
  '/sell-exit/new': typeof AuthenticatedSellExitNewRoute
  '/sell-exit/status': typeof AuthenticatedSellExitStatusRoute
  '/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/staff/users': typeof AuthenticatedStaffUsersRoute
  '/new-units/live/$id': typeof NewUnitsLiveIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff/verification/$id': typeof AuthenticatedStaffVerificationIdRoute
  '/staff/verification': typeof AuthenticatedStaffVerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sale': typeof SaleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/exit-opportunities/$slug': typeof ExitOpportunitiesSlugRoute
  '/new-units/$slug': typeof NewUnitsSlugRoute
  '/project-opportunities/$slug': typeof ProjectOpportunitiesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/exit-opportunities/': typeof ExitOpportunitiesIndexRoute
  '/new-units/': typeof NewUnitsIndexRoute
  '/project-opportunities/': typeof ProjectOpportunitiesIndexRoute
  '/sell-exit/': typeof SellExitIndexRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/nav': typeof AuthenticatedAdminNavRoute
  '/_authenticated/admin/new-units': typeof AuthenticatedAdminNewUnitsRoute
  '/_authenticated/admin/project-opportunities': typeof AuthenticatedAdminProjectOpportunitiesRoute
  '/_authenticated/dashboard/exit-requests': typeof AuthenticatedDashboardExitRequestsRoute
  '/_authenticated/sell-exit/new': typeof AuthenticatedSellExitNewRoute
  '/_authenticated/sell-exit/status': typeof AuthenticatedSellExitStatusRoute
  '/_authenticated/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/_authenticated/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/_authenticated/staff/users': typeof AuthenticatedStaffUsersRoute
  '/new-units/live/$id': typeof NewUnitsLiveIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/verification/$id': typeof AuthenticatedStaffVerificationIdRoute
  '/_authenticated/staff/verification/': typeof AuthenticatedStaffVerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/properties'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sale'
    | '/admin'
    | '/dashboard/inquiries'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/exit-opportunities/$slug'
    | '/new-units/$slug'
    | '/project-opportunities/$slug'
    | '/property/$slug'
    | '/exit-opportunities/'
    | '/new-units/'
    | '/project-opportunities/'
    | '/sell-exit/'
    | '/admin/catalog'
    | '/admin/cities'
    | '/admin/content'
    | '/admin/crm'
    | '/admin/forms'
    | '/admin/media'
    | '/admin/nav'
    | '/admin/new-units'
    | '/admin/project-opportunities'
    | '/dashboard/exit-requests'
    | '/sell-exit/new'
    | '/sell-exit/status'
    | '/staff/audit'
    | '/staff/settings'
    | '/staff/users'
    | '/new-units/live/$id'
    | '/admin/'
    | '/staff/verification/$id'
    | '/staff/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/properties'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sale'
    | '/dashboard/inquiries'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/exit-opportunities/$slug'
    | '/new-units/$slug'
    | '/project-opportunities/$slug'
    | '/property/$slug'
    | '/exit-opportunities'
    | '/new-units'
    | '/project-opportunities'
    | '/sell-exit'
    | '/admin/catalog'
    | '/admin/cities'
    | '/admin/content'
    | '/admin/crm'
    | '/admin/forms'
    | '/admin/media'
    | '/admin/nav'
    | '/admin/new-units'
    | '/admin/project-opportunities'
    | '/dashboard/exit-requests'
    | '/sell-exit/new'
    | '/sell-exit/status'
    | '/staff/audit'
    | '/staff/settings'
    | '/staff/users'
    | '/new-units/live/$id'
    | '/admin'
    | '/staff/verification/$id'
    | '/staff/verification'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/properties'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sale'
    | '/_authenticated/admin'
    | '/dashboard/inquiries'
    | '/dashboard/profile'
    | '/dashboard/properties'
    | '/exit-opportunities/$slug'
    | '/new-units/$slug'
    | '/project-opportunities/$slug'
    | '/property/$slug'
    | '/exit-opportunities/'
    | '/new-units/'
    | '/project-opportunities/'
    | '/sell-exit/'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/forms'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/nav'
    | '/_authenticated/admin/new-units'
    | '/_authenticated/admin/project-opportunities'
    | '/_authenticated/dashboard/exit-requests'
    | '/_authenticated/sell-exit/new'
    | '/_authenticated/sell-exit/status'
    | '/_authenticated/staff/audit'
    | '/_authenticated/staff/settings'
    | '/_authenticated/staff/users'
    | '/new-units/live/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/verification/$id'
    | '/_authenticated/staff/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PropertiesRoute: typeof PropertiesRoute
  RegisterRoute: typeof RegisterRoute
  RentRoute: typeof RentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaleRoute: typeof SaleRoute
  ExitOpportunitiesSlugRoute: typeof ExitOpportunitiesSlugRoute
  NewUnitsSlugRoute: typeof NewUnitsSlugRoute
  ProjectOpportunitiesSlugRoute: typeof ProjectOpportunitiesSlugRoute
  PropertySlugRoute: typeof PropertySlugRoute
  ExitOpportunitiesIndexRoute: typeof ExitOpportunitiesIndexRoute
  NewUnitsIndexRoute: typeof NewUnitsIndexRoute
  ProjectOpportunitiesIndexRoute: typeof ProjectOpportunitiesIndexRoute
  SellExitIndexRoute: typeof SellExitIndexRoute
  NewUnitsLiveIdRoute: typeof NewUnitsLiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/exit-opportunities/': {
      id: '/exit-opportunities/'
      path: '/exit-opportunities'
      fullPath: '/exit-opportunities/'
      preLoaderRoute: typeof ExitOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exit-opportunities/$slug': {
      id: '/exit-opportunities/$slug'
      path: '/exit-opportunities/$slug'
      fullPath: '/exit-opportunities/$slug'
      preLoaderRoute: typeof ExitOpportunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-units/': {
      id: '/new-units/'
      path: '/new-units'
      fullPath: '/new-units/'
      preLoaderRoute: typeof NewUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-units/$slug': {
      id: '/new-units/$slug'
      path: '/new-units/$slug'
      fullPath: '/new-units/$slug'
      preLoaderRoute: typeof NewUnitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-opportunities/': {
      id: '/project-opportunities/'
      path: '/project-opportunities'
      fullPath: '/project-opportunities/'
      preLoaderRoute: typeof ProjectOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-opportunities/$slug': {
      id: '/project-opportunities/$slug'
      path: '/project-opportunities/$slug'
      fullPath: '/project-opportunities/$slug'
      preLoaderRoute: typeof ProjectOpportunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-exit/': {
      id: '/sell-exit/'
      path: '/sell-exit'
      fullPath: '/sell-exit/'
      preLoaderRoute: typeof SellExitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/forms': {
      id: '/_authenticated/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nav': {
      id: '/_authenticated/admin/nav'
      path: '/nav'
      fullPath: '/admin/nav'
      preLoaderRoute: typeof AuthenticatedAdminNavRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new-units': {
      id: '/_authenticated/admin/new-units'
      path: '/new-units'
      fullPath: '/admin/new-units'
      preLoaderRoute: typeof AuthenticatedAdminNewUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/project-opportunities': {
      id: '/_authenticated/admin/project-opportunities'
      path: '/project-opportunities'
      fullPath: '/admin/project-opportunities'
      preLoaderRoute: typeof AuthenticatedAdminProjectOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/exit-requests': {
      id: '/_authenticated/dashboard/exit-requests'
      path: '/dashboard/exit-requests'
      fullPath: '/dashboard/exit-requests'
      preLoaderRoute: typeof AuthenticatedDashboardExitRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell-exit/new': {
      id: '/_authenticated/sell-exit/new'
      path: '/sell-exit/new'
      fullPath: '/sell-exit/new'
      preLoaderRoute: typeof AuthenticatedSellExitNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell-exit/status': {
      id: '/_authenticated/sell-exit/status'
      path: '/sell-exit/status'
      fullPath: '/sell-exit/status'
      preLoaderRoute: typeof AuthenticatedSellExitStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/audit': {
      id: '/_authenticated/staff/audit'
      path: '/staff/audit'
      fullPath: '/staff/audit'
      preLoaderRoute: typeof AuthenticatedStaffAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/settings': {
      id: '/_authenticated/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof AuthenticatedStaffSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/users': {
      id: '/_authenticated/staff/users'
      path: '/staff/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof AuthenticatedStaffUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/new-units/live/$id': {
      id: '/new-units/live/$id'
      path: '/new-units/live/$id'
      fullPath: '/new-units/live/$id'
      preLoaderRoute: typeof NewUnitsLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/verification/': {
      id: '/_authenticated/staff/verification/'
      path: '/staff/verification'
      fullPath: '/staff/verification/'
      preLoaderRoute: typeof AuthenticatedStaffVerificationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/verification/$id': {
      id: '/_authenticated/staff/verification/$id'
      path: '/staff/verification/$id'
      fullPath: '/staff/verification/$id'
      preLoaderRoute: typeof AuthenticatedStaffVerificationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNavRoute: typeof AuthenticatedAdminNavRoute
  AuthenticatedAdminNewUnitsRoute: typeof AuthenticatedAdminNewUnitsRoute
  AuthenticatedAdminProjectOpportunitiesRoute: typeof AuthenticatedAdminProjectOpportunitiesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNavRoute: AuthenticatedAdminNavRoute,
  AuthenticatedAdminNewUnitsRoute: AuthenticatedAdminNewUnitsRoute,
  AuthenticatedAdminProjectOpportunitiesRoute:
    AuthenticatedAdminProjectOpportunitiesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardExitRequestsRoute: typeof AuthenticatedDashboardExitRequestsRoute
  AuthenticatedSellExitNewRoute: typeof AuthenticatedSellExitNewRoute
  AuthenticatedSellExitStatusRoute: typeof AuthenticatedSellExitStatusRoute
  AuthenticatedStaffAuditRoute: typeof AuthenticatedStaffAuditRoute
  AuthenticatedStaffSettingsRoute: typeof AuthenticatedStaffSettingsRoute
  AuthenticatedStaffUsersRoute: typeof AuthenticatedStaffUsersRoute
  AuthenticatedStaffVerificationIdRoute: typeof AuthenticatedStaffVerificationIdRoute
  AuthenticatedStaffVerificationIndexRoute: typeof AuthenticatedStaffVerificationIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardExitRequestsRoute:
    AuthenticatedDashboardExitRequestsRoute,
  AuthenticatedSellExitNewRoute: AuthenticatedSellExitNewRoute,
  AuthenticatedSellExitStatusRoute: AuthenticatedSellExitStatusRoute,
  AuthenticatedStaffAuditRoute: AuthenticatedStaffAuditRoute,
  AuthenticatedStaffSettingsRoute: AuthenticatedStaffSettingsRoute,
  AuthenticatedStaffUsersRoute: AuthenticatedStaffUsersRoute,
  AuthenticatedStaffVerificationIdRoute: AuthenticatedStaffVerificationIdRoute,
  AuthenticatedStaffVerificationIndexRoute:
    AuthenticatedStaffVerificationIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardInquiriesRoute: typeof DashboardInquiriesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInquiriesRoute: DashboardInquiriesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPropertiesRoute: DashboardPropertiesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PropertiesRoute: PropertiesRoute,
  RegisterRoute: RegisterRoute,
  RentRoute: RentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaleRoute: SaleRoute,
  ExitOpportunitiesSlugRoute: ExitOpportunitiesSlugRoute,
  NewUnitsSlugRoute: NewUnitsSlugRoute,
  ProjectOpportunitiesSlugRoute: ProjectOpportunitiesSlugRoute,
  PropertySlugRoute: PropertySlugRoute,
  ExitOpportunitiesIndexRoute: ExitOpportunitiesIndexRoute,
  NewUnitsIndexRoute: NewUnitsIndexRoute,
  ProjectOpportunitiesIndexRoute: ProjectOpportunitiesIndexRoute,
  SellExitIndexRoute: SellExitIndexRoute,
  NewUnitsLiveIdRoute: NewUnitsLiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
